ENT.Base 			= "npc_vj_emp_m2browning"
ENT.Type 			= "ai"
ENT.PrintName 		= "Friendly M2 Browning Emplacement"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Emplacements"