ENT.Base 			= "npc_vj_mili_emp_mg42"
ENT.Type 			= "ai"
ENT.PrintName 		= "Friendly MG 42 Emplacement"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Military"